### ISSUE TITLE
General inconsistencies and typos

### ISSUE THREAD

**Issue by BC46** [BC46/freelancer-text-strings-revision#3]
- [x] Landwarhkanal -> Landwehrkanal
- [x] Schroder -> Schröder
- [x] Hanover -> Hannover
- [x] Wendell -> Weddell
- [x] String ID 21946 looks a bit weird in-game
- [x] Kruger -> Krüger
- [x] Koeln -> Köln
- [x] Capitalize all audio setting names

**Comment by erikroe** [comment]
There is actually a lot of more NPC names with issues I saw recently. A bit too much to just list them separately. And all "Kruger" must be set to "Krüger" if one wants to make it right. Some capship names are also inconsistent, like "Koeln", "Köln" which is just the same.
